
''' problem #2 -- Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.'''


fib = [1, 2] #, 3, 5, 8, 13, 21, 34, 55, 89]

# given first 10 Fibonacco numbers, append remaining numbers up to 4 million
i = fib[len(fib)-1]
while i < 4000000:
    i += fib[len(fib)-2]
    fib.append(i)

# identify even Fibonacci numbers
evens = []
sum = 0
for j in fib:
    if (j % 2) == 0:
        evens.append(j)
        sum += j

# print results
print fib
print evens
print sum